name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/vertig0ne/middy-test:latest
    - name: Docker login
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u github-ci --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/vertig0ne/middy-test:latest
